# DEFAULT RDBMS: Connection Details
#---------------------------------------------------

development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: opt_development
  pool: 20
  username: root
  password:
  wait_timeout: 2147483
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: opt_development
  pool: 20
  username: root
  password:
  wait_timeout: 2147483
  host: 127.0.0.1
