
production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    min_memory: 512M
    max_memory: 1G
    
test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING

    