
production:
  solr:
    hostname: localhost
    port: 8973
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8972
    log_level: INFO
    min_memory: 512M
    max_memory: 1G
    
test:
  solr:
    hostname: localhost
    port: 8971
    log_level: WARNING

    